import { NgModule } from '@angular/core';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {MzBadgeModule,
  MzButtonModule,
  MzCardModule,
  MzCheckboxModule,
  MzChipModule,
  MzCollapsibleModule ,
  MzCollectionModule,
  MzDatepickerModule,
  MzValidationModule ,
  MzInputModule ,
  MzIconModule,
  MzRadioButtonModule ,
  MzSelectModule ,
  MzSwitchModule ,
  MzTextareaModule ,
  MzTimepickerModule ,
  MzDropdownModule ,
  MzModalModule ,
  MzNavbarModule ,
  MzPaginationModule ,
  MzParallaxModule ,
  MzSidenavModule ,
  MzTabModule ,
  MzProgressModule ,
  MzSpinnerModule ,
  MzMediaModule } from 'ngx-materialize';

@NgModule({
  exports: [
    MzBadgeModule,
    MzButtonModule,
    MzCardModule,
    MzCheckboxModule,
    MzChipModule,
    MzCollapsibleModule ,
    MzCollectionModule,
    MzDatepickerModule,
    MzValidationModule ,
    MzInputModule ,
    MzIconModule,
    MzRadioButtonModule ,
    MzSelectModule ,
    MzSwitchModule ,
    MzTextareaModule ,
    MzTimepickerModule ,
    MzDropdownModule ,
    MzModalModule ,
    MzNavbarModule ,
    MzPaginationModule ,
    MzParallaxModule ,
    MzSidenavModule ,
    MzTabModule ,
    MzProgressModule ,
    MzSpinnerModule ,
    MzMediaModule ,
  ],
  declarations: []
})
export class MaterialModule { }
